services:
  db:
    image: mysql:9.0
    container_name: domakina-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - domakina_mysql_data:/var/lib/mysql
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "db",
          "-u",
          "${DB_USER}",
          "-p${DB_PASSWORD}",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - domakina_network

  minio:
    image: minio/minio:latest
    container_name: domakina-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT}:9000" # API Port
      - "${MINIO_CONSOLE_PORT}:9001" # Web UI Port
    volumes:
      - domakina_minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - domakina_network
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://domakina-minio:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  # frontend:
  #   container_name: domakina-frontend
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${FRONTEND_PORT}:80"
  #   networks:
  #     - domakina_network
  #   env_file:
  #     - ../frontend/.env

  # backend:
  #   container_name: domakina-backend
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${BACKEND_PORT}:4000"
  #   networks:
  #     - domakina_network
  #   env_file:
  #     - ../backend/.env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     minio:
  #       condition: service_healthy

volumes:
  domakina_mysql_data:
    driver: local
  domakina_minio_data:
    driver: local

networks:
  domakina_network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
